apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: apache-php:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_USER
          value: appuser
        - name: DB_PASSWORD
          value: apppass
        - name: DB_NAME
          value: appdb
        ports:
        - containerPort: 80

